services:
  media-nginx:
    build:
      context: nginx
      dockerfile: nginx-dockerfile
    ports:
      - 7000:80
    environment:
      MINIO_ENDPOINT: http://media-minio:9000
  media:
    extends:
      file: docker-compose-base.yaml
      service: media
    build:
      context: .
      dockerfile: devcontainer-dockerfile
    ports:
      - 8080:8080
    environment:
      MINIO_ENDPOINT: http://media-minio:9000
  media-minio:
    extends:
      file: docker-compose-base.yaml
      service: media-minio
    ports:
      - 9000:9000
      - 9090:9090
  media-dapr:
    extends:
      file: docker-compose-base.yaml
      service: media-dapr
    volumes:
      - "./.dapr/dapr-config-minimal.yaml:/config.yaml"
      - "./.dapr/components:/components"
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - 50006:50006
volumes:
  media-minio-data:
