services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  media:
    restart: unless-stopped
    build:
      context: .
      dockerfile: base-dockerfile
    healthcheck:
      test: wget http://localhost:8080/graphiql || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    depends_on:
      - media-minio
    environment:
      MONGODB_URI: mongodb://media-db:27017
  media-minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_REGION: eu-central-1
    volumes:
      - media-minio-data:/data
    command: server --console-address ":9090" /data
  media-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "--app-id",
        "media",
        "--app-port",
        "8080",
        "--app-protocol",
        "http",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path",
        "/components",
      ]
    network_mode: "service:media"
volumes:
  media-minio-data:
